import { Category, Product, StoreSettings } from './types';

export const INITIAL_SETTINGS: StoreSettings = {
  store_name: 'Apex Tools & Hardware Supply',
  tagline: 'Your Trusted Partner in Building, Power Tools & Industrial Hardware',
  whatsapp_number: '15551234567',
  phone: '+1 (555) 123-4567',
  email: 'sales@apexhardware.com',
  address: '128 Industrial Parkway, Builder District',
  opening_hours: 'Mon - Sat: 7:30 AM - 6:30 PM | Sun: 8:00 AM - 2:00 PM',
  announcement_banner: '⚡ Contractor Discounts on Bulk Orders! WhatsApp us for instant trade quotes.',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Power Tools',
    slug: 'power-tools',
    description: 'Cordless drills, angle grinders, demolition hammers & saws',
    icon: 'Hammer',
    image_url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80',
    display_order: 1,
  },
  {
    id: 'cat-2',
    name: 'Hand Tools',
    slug: 'hand-tools',
    description: 'Mechanics sets, wrenches, ratchets, pliers & screwdrivers',
    icon: 'Wrench',
    image_url: 'https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=600&q=80',
    display_order: 2,
  },
  {
    id: 'cat-3',
    name: 'Plumbing & Pipes',
    slug: 'plumbing',
    description: 'PVC pipes, brass ball valves, copper fittings & pumps',
    icon: 'Droplet',
    image_url: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=600&q=80',
    display_order: 3,
  },
  {
    id: 'cat-4',
    name: 'Electrical & Lighting',
    slug: 'electrical',
    description: 'Breaker panels, industrial cable, switches & LED floodlights',
    icon: 'Zap',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
    display_order: 4,
  },
  {
    id: 'cat-5',
    name: 'Building Materials',
    slug: 'building-materials',
    description: 'Drywall fasteners, structural adhesives, rebar & concrete supplies',
    icon: 'Building2',
    image_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80',
    display_order: 5,
  },
  {
    id: 'cat-6',
    name: 'Paints & Coatings',
    slug: 'paints',
    description: 'Industrial primers, weatherproof acrylics, brushes & sealers',
    icon: 'Paintbrush',
    image_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    display_order: 6,
  },
  {
    id: 'cat-7',
    name: 'Safety & Fasteners',
    slug: 'safety-fasteners',
    description: 'Hard hats, high-vis vests, anchors, nuts, bolts & safety goggles',
    icon: 'ShieldCheck',
    image_url: 'https://images.unsplash.com/photo-1578873375955-467f53fd7f67?auto=format&fit=crop&w=600&q=80',
    display_order: 7,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'DeWalt 20V MAX Brushless Cordless Drill / Driver Kit',
    slug: 'dewalt-20v-max-brushless-cordless-drill',
    sku: 'PT-DW20V-01',
    category_slug: 'power-tools',
    brand: 'DeWalt',
    price: 149.99,
    discount_price: 129.99,
    unit: 'kit',
    stock_quantity: 24,
    stock_status: 'in_stock',
    is_featured: true,
    is_popular: true,
    description: 'High-performance brushless motor delivers 340 unit watts out (UWO) of power. Compact, lightweight design fits into tight areas with ergonomic comfort grip handle. Comes with 2x 20V Li-Ion batteries, fast charger, and heavy-duty contractor bag.',
    image_url: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
    additional_images: [
      'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80',
    ],
    specifications: {
      'Voltage': '20V MAX',
      'Motor Type': 'Brushless',
      'Battery Included': '2x 2.0Ah Lithium-Ion',
      'Chuck Size': '1/2 inch Keyless Metal',
      'Speed Settings': '2-Speed (0-450 / 0-1,650 RPM)',
      'Warranty': '3 Years Manufacturer Warranty',
    },
  },
  {
    id: 'prod-2',
    title: 'Bosch 4.5-Inch 11-Amp Heavy Duty Angle Grinder',
    slug: 'bosch-4-5-inch-11-amp-angle-grinder',
    sku: 'PT-BSH-AG45',
    category_slug: 'power-tools',
    brand: 'Bosch',
    price: 89.00,
    discount_price: 79.50,
    unit: 'piece',
    stock_quantity: 18,
    stock_status: 'in_stock',
    is_featured: true,
    is_popular: false,
    description: 'Powerful 11 Amp motor producing up to 11,500 RPM for fast material removal and cutting through tough steel, masonry, and rebar. Engineered with direct-motor cooling and vibration-control handle.',
    image_url: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Amperage': '11.0A',
      'Disc Diameter': '4-1/2 Inch (115mm)',
      'No Load RPM': '11,500 RPM',
      'Spindle Thread': '5/8"-11',
      'Weight': '4.8 lbs',
    },
  },
  {
    id: 'prod-3',
    title: 'Stanley 200-Piece Mechanics Socket & Ratchet Tool Set',
    slug: 'stanley-200-piece-mechanics-socket-tool-set',
    sku: 'HT-STN-200S',
    category_slug: 'hand-tools',
    brand: 'Stanley',
    price: 119.00,
    discount_price: 99.00,
    unit: 'set',
    stock_quantity: 12,
    stock_status: 'in_stock',
    is_featured: true,
    is_popular: true,
    description: 'Complete master mechanics tool set crafted with high-polish chrome vanadium steel for maximum corrosion resistance and durability. Includes 1/4", 3/8", and 1/2" quick-release pear ratchets.',
    image_url: 'https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Total Pieces': '200 Pieces',
      'Material': 'Forged Chrome Vanadium Steel',
      'Drive Sizes': '1/4", 3/8", 1/2" Ratchets',
      'Measurement Standard': 'SAE & Metric',
      'Storage': 'Molded Heavy Duty Carry Case',
    },
  },
  {
    id: 'prod-4',
    title: 'Heavy-Duty Brass Full-Port Ball Valve (3/4 Inch)',
    slug: 'heavy-duty-brass-ball-valve-3-4-inch',
    sku: 'PL-BV-34BR',
    category_slug: 'plumbing',
    brand: 'ApexPlumb',
    price: 14.50,
    discount_price: null,
    unit: 'piece',
    stock_quantity: 85,
    stock_status: 'in_stock',
    is_featured: false,
    is_popular: true,
    description: 'Solid forged brass construction with PTFE seals and rust-resistant vinyl grip handle. Full port design ensures maximum water flow with minimal pressure drop.',
    image_url: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Connection': '3/4" Female NPT x Female NPT',
      'Body Material': 'Forged Brass (Lead-Free Compliant)',
      'Pressure Rating': '600 PSI WOG / 150 PSI WSP',
      'Handle': 'Corrosion-Resistant Zinc Plated Steel Lever',
    },
  },
  {
    id: 'prod-5',
    title: 'Industrial Grade Schedule 40 PVC Pressure Pipe (2" x 10ft)',
    slug: 'industrial-grade-pvc-pipe-2-inch-10ft',
    sku: 'PL-PVC-2IN10',
    category_slug: 'plumbing',
    brand: 'PipePro',
    price: 18.75,
    discount_price: null,
    unit: 'piece',
    stock_quantity: 120,
    stock_status: 'in_stock',
    is_featured: false,
    is_popular: false,
    description: 'Rigid PVC Schedule 40 pipe suitable for potable cold water pressure systems, commercial plumbing, and irrigation. Non-toxic, highly chemical resistant.',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Diameter': '2 Inch Nominal',
      'Length': '10 Feet',
      'Wall Thickness': 'SCH 40 Standard',
      'Certification': 'NSF 61 Certified for Potable Water',
    },
  },
  {
    id: 'prod-6',
    title: 'Schneider 200A 24-Space Main Breaker Distribution Panel',
    slug: 'schneider-200a-main-breaker-distribution-panel',
    sku: 'EL-SCH-200A',
    category_slug: 'electrical',
    brand: 'Schneider Electric',
    price: 185.00,
    discount_price: 165.00,
    unit: 'piece',
    stock_quantity: 8,
    stock_status: 'in_stock',
    is_featured: true,
    is_popular: false,
    description: 'Indoor surface/flush load center panel with factory-installed 200 Amp main circuit breaker. Solid copper bus bars for high conductivity and long electrical service life.',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Main Rating': '200 Amperes',
      'Capacity': '24 Spaces / 48 Tandem Circuits',
      'Voltage': '120/240V AC Single Phase',
      'Enclosure': 'NEMA 1 Indoor Steel',
    },
  },
  {
    id: 'prod-7',
    title: 'High-Strength Structural Drywall & Wood Screws (Box of 1,000)',
    slug: 'structural-drywall-wood-screws-box-1000',
    sku: 'BM-SCR-DW1000',
    category_slug: 'building-materials',
    brand: 'FastenMax',
    price: 28.50,
    discount_price: 24.99,
    unit: 'box',
    stock_quantity: 50,
    stock_status: 'in_stock',
    is_featured: false,
    is_popular: true,
    description: 'Bugle-head coarse thread black phosphate coated screws. Sharp piercing point enables quick driving into timber and light gauge steel without splitting.',
    image_url: 'https://images.unsplash.com/photo-1586864387967-d02ef85d93e8?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Box Count': '1,000 Screws',
      'Size': '#6 x 1-5/8 Inch',
      'Drive Type': '#2 Phillips Head',
      'Finish': 'Corrosion-Resistant Black Phosphate',
    },
  },
  {
    id: 'prod-8',
    title: 'All-Weather Exterior Weatherproof Wall Primer & Sealer (5 Gal)',
    slug: 'all-weather-exterior-wall-primer-5gal',
    sku: 'PT-EXT-PRM5',
    category_slug: 'paints',
    brand: 'DuraCoat Pro',
    price: 84.00,
    discount_price: null,
    unit: 'bucket',
    stock_quantity: 15,
    stock_status: 'in_stock',
    is_featured: false,
    is_popular: false,
    description: '100% acrylic exterior primer that bonds tenaciously to concrete, masonry, brick, and siding. Seals porous surfaces and provides an ultra-durable foundation.',
    image_url: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Container Size': '5 Gallon Bucket (18.9 Liters)',
      'Coverage': '1,500 - 2,000 sq ft per bucket',
      'Base': '100% Acrylic Water-Based',
      'Application': 'Brush, Roller, or Airless Spray',
    },
  },
  {
    id: 'prod-9',
    title: 'OSHA-Certified Construction Hard Hat & High-Vis Vest Kit',
    slug: 'osha-certified-safety-hard-hat-high-vis-kit',
    sku: 'SF-KIT-OSHA01',
    category_slug: 'safety-fasteners',
    brand: 'GuardMaster',
    price: 34.99,
    discount_price: 29.99,
    unit: 'set',
    stock_quantity: 40,
    stock_status: 'in_stock',
    is_featured: true,
    is_popular: true,
    description: 'Industrial safety bundle with ventilated ANSI-compliant safety helmet, comfortable 6-point ratchet dial suspension, ANSI Class 2 neon safety vest, and UV400 wrap-around safety glasses.',
    image_url: 'https://images.unsplash.com/photo-1578873375955-467f53fd7f67?auto=format&fit=crop&w=800&q=80',
    specifications: {
      'Helmet Rating': 'ANSI/ISEA Z89.1 Type 1 Class C',
      'Vest Standard': 'ANSI/ISEA 107-2020 Class 2 High-Vis',
      'Suspension': '6-Point Adjustable Ratchet Dial',
      'Package Includes': '1x Hard Hat, 1x Reflective Vest, 1x Safety Glasses',
    },
  },
];
